[workspace]
name = "pm-pixi"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
cmake = "*"
ninja = "*"
fmt = "*"
cxx-compiler = "*"
pkg-config = "*"
cgal = "*"

[tasks]
configure = "cmake -S . -B build -G Ninja"
build = "cmake --build build"
run = "./build/app"
