#cloud-config
package_update: true
package_upgrade: true
packages:
  - git
  - curl
  - ca-certificates
  - cmake
  - ninja-build
  - build-essential
  - gdb
  - pkg-config
  - unzip
  - tar
runcmd:
  - [ sh, -lc, "echo cloud-init complete" ]
